name: Publish

on:
  workflow_run:
    workflows: ['Web Test Runner']
    branches: [main]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - run: echo //registry.npmjs.org/:_authToken=${NPM_AUTH_TOKEN} > .npmrc
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

      - name: Bootstrap
        run: npm ci

      - name: Publish
        run: npx lerna publish --canary --preid canary.$(date +"%s") --dist-tag canary --yes
