name: Web Test Runner

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Bootstrap
        run: npm ci

      - name: Lib Tests
        run: npx lerna run test

      - name: Build Integration (Own)
        run: npx tsc -p integration/todo-own && npx vite build integration/todo-own

      - name: Build Integration (Mixed)
        run: npx tsc -p integration/todo-mixed && npx vite build integration/todo-mixed
